using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using Selenium.Pages;
using System.Threading;

namespace Selenium.Tests
{
    internal class DraftFunctionalityTests : BaseTest
    {
        private const string _logIn = "eugenebondthe@tutanota.com";
        private const string _password = "KbKjBcNbXkJkJ891?";
        private const string _mailSendingPassword = "Qwerty123!?@";

        private MainPage _mainPage;
        private LoginPage _loginPage;
        private HomePage _homePage;
        
        string _autoGeneratedString;
        string adressee;

        [SetUp]
        public void Before()
        {
            _mainPage = new MainPage(driver);
            _loginPage = new LoginPage(driver);
            _homePage = new HomePage(driver);

            var random = new Random();
            adressee = $"user{random.Next(0, 100)}@gmail.com";

            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var stringChars = new char[15];

            for (int i = 0; i < stringChars.Length; i++)
            {
                stringChars[i] = chars[random.Next(chars.Length)];
            }

            _autoGeneratedString = new String(stringChars);
        }

        [Test(Description = "Verify that user can create and save new mail to Draft folder")]
        public void NewDraftMailCreation()
        {
            _mainPage.OpenLoginPage();
            _loginPage.Login(_logIn, _password);
            _homePage.CreateNewEmailAsDraft(adressee, _autoGeneratedString);
            _homePage.OpenDraftsPage();
            Assert.IsTrue(_homePage.ValidateDraftMailSave(_autoGeneratedString));
        }

        [Test(Description = "Verify that user can create, save new mail to Draft folder and send it")]
        public void NewDraftMailCreationAndSending()
        {
            _mainPage.OpenLoginPage();
            _loginPage.Login(_logIn, _password);
            _homePage.CreateNewEmailAsDraft(adressee, _autoGeneratedString);
            _homePage.OpenDraftsPage();
            _homePage.OpenAndSendCreatedDraftMail(_autoGeneratedString, _mailSendingPassword);
            Assert.IsTrue(_homePage.ValidateMailSend(_autoGeneratedString));
        }
    }
}
